spring.application.name=back-end
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:mysql://localhost:3306/generation_express
spring.datasource.username=root
spring.datasource.password=Rig0bert0.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true






